spring:
  application:
    name: news-scanner
  data:
    mongodb:
      port: ${MONGO_DB_PORT}
      username: ${MONGO_DB_USER_NAME}
      database: ${MONGO_DB_NAME}
      password: ${MONGO_DB_PASSWORD}
      host: ${MONGO_DB_HOST}
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      authentication-database: admin

application:
  chrome: ./chromedriver